---  
spring:  
  profiles: peer1                                 # 指定profile=peer1  
  application:  
    name: Eureka-Server1
server:  
  port: 8761   # 注册服务的端口号  
eureka:  
  instance:  
    hostname: peer1                               # 指定当profile=peer1时，主机名
  client:  
    serviceUrl:  
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/      # 将自己注册到peer2这个Eureka上面去
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: peer2
  application:
    name: Eureka-Server2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/ # 将自己注册到peer1这个Eureka上面去
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: peer3
  application:
    name: Eureka-Server3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ # 将自己注册到peer1这个Eureka上面去
    register-with-eureka: false
    fetch-registry: false

#    注意:在host文件中添加：
#    127.0.0.1 peer1
#    127.0.0.1 peer2
#    127.0.0.1 peer3